# Generated by Django 2.2.3 on 2019-08-05 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[(1, 'Główne'), (2, 'Akcesoryjne'), (3, 'Korekcyjne')], default=1, max_length=1)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('how_many_series', models.IntegerField(null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.GymExercise')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(null=True)),
                ('load', models.IntegerField(null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.Week')),
            ],
        ),
        migrations.CreateModel(
            name='PartialPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exercises', models.ManyToManyField(to='training.GymExercise')),
                ('main_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='training.MainPlan')),
            ],
        ),
    ]
