# Generated by Django 2.2.3 on 2019-08-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymexercise',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mainplan',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
