# Generated by Django 2.2.4 on 2019-08-06 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20190805_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='partial_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='training.PartialPlan'),
            preserve_default=False,
        ),
    ]
