# Generated by Django 2.2.4 on 2019-08-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_week_partial_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialplan',
            name='main_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.MainPlan'),
        ),
        migrations.AlterField(
            model_name='series',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.GymExercise'),
        ),
        migrations.AlterField(
            model_name='week',
            name='partial_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.PartialPlan'),
        ),
    ]
