# Generated by Django 2.2.4 on 2019-08-08 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_partialplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partialplan',
            name='user',
        ),
    ]
