# Generated by Django 2.2.4 on 2019-08-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_partialplan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymexercise',
            name='movie_link',
            field=models.TextField(null=True),
        ),
    ]
